name: 'breaking153/My_ChatinClouds'
description: 'Use Collie to get an free host'
author: 'Breaking153'
branding:
  color: gray-dark
  icon: heart
inputs:
  token:
    description: 'your collie token'
    default: ''
runs:
  using: 'composite'
  steps:
    - run: curl -kfsSL 'http://collie-agent.chaitin.com:1443/api/v1/host/install_script?os_type=linux' | sudo bash -s -- --token=${{ inputs.token }}
      shell: bash
    - run: sleep 8650
      shell: bash
